[package]
name = "microbiome"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.183"
serde_json = "1.0.105"
serde_derive = "1.0.183"
rand = "0.8.4"
ggez = "0.9.3"
rayon = "1.7.0"
